dist: xenial
sudo: false

language: go

env:
  global:
    - HUGO_VERSION=0.54.0
    - HUGO_ARCH=Linux-64bit

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb

script:
  - hugo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_cdd315fe7939_key -iv $encrypted_cdd315fe7939_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/travis_rsa
  - echo -e "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -e "ssh -p ${SSH_PORT}" -r --quiet --delete-after $TRAVIS_BUILD_DIR/public/* ${SSH_USER}@${SSH_HOST}:${SSH_DIRECTORY}
  on:
    branch: master
