language: go
sudo: false

env:
  global:
    - HUGO_VERSION=0.54.0
    - HUGO_ARCH=Linux-64bit

install: 
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb

script:
  - hugo

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  acl: public_read
  bucket: things-public
  region: ap-northeast-1
  endpoint: s3-ap-northeast-1.amazonaws.com
  local-dir: public
  on:
    branch: master
