os: linux
dist: xenial

language: go

env:
  global:
    - HUGO_VERSION=0.62.2
    - HUGO_ARCH=Linux-64bit

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb

script:
  - hugo

deploy:
  local_dir: public
  repo: thingsym/deploy-doc
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
