name: publish to github pages

on:
  create:
    tags:
      - v*.*.*
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install hugo
        run: |
          curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-64bit.tar.gz | tar -xz
          sudo mv hugo /usr/local/bin/hugo
        env:
          HUGO_VERSION: 0.62.2
 
      - name: build
        run: hugo

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          publish_dir: ./public
          commit_message: 'deploy to GitHub Pages via GitHub Actions'
